# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Header

class Cmds(object):
    Register = 0
    Stage1_data_ready = 1
    Stage2_data_ready = 2
    Stage3_data_ready = 3
    Stage1_data = 4
    Web_server_data = 5

