# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Header

class Stages(object):
    Stage1 = 0
    Stage2 = 1
    Stage3 = 2
    WebServer = 3
    BIG_BROTHER = 4
    BACKBONE_SERVER = 5

