# Generated by Django 3.1.6 on 2021-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandbuddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='color',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='genre',
            field=models.CharField(choices=[('rock', 'ROCK'), ('jazz', 'JAZZ'), ('funk', 'FUNK'), ('pop', 'POP'), ('classical', 'CLASSICAL')], default='rock', max_length=10),
        ),
    ]
