# Generated by Django 3.1.6 on 2021-02-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandbuddy', '0003_auto_20210219_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.CharField(choices=[('rock', 'ROCK'), ('jazz', 'JAZZ'), ('funk', 'FUNK'), ('pop', 'POP'), ('classical', 'CLASSICAL')], default='rock', max_length=10),
        ),
    ]
