# Generated by Django 3.1.6 on 2021-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandbuddy', '0004_auto_20210219_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('rock', 'ROCK'), ('jazz', 'JAZZ'), ('funk', 'FUNK'), ('pop', 'POP'), ('classical', 'CLASSICAL')], default='rock', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
