# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WebServer_Stage3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WebServerStage3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WebServerStage3()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWebServerStage3(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WebServerStage3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WebServerStage3
    def Drums(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WebServerStage3
    def Guitar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def WebServerStage3Start(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddDrums(builder, drums): builder.PrependUint8Slot(0, drums, 0)
def WebServerStage3AddDrums(builder, drums):
    """This method is deprecated. Please switch to AddDrums."""
    return AddDrums(builder, drums)
def AddGuitar(builder, guitar): builder.PrependUint8Slot(1, guitar, 0)
def WebServerStage3AddGuitar(builder, guitar):
    """This method is deprecated. Please switch to AddGuitar."""
    return AddGuitar(builder, guitar)
def End(builder): return builder.EndObject()
def WebServerStage3End(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)