# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WebServer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WebServer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WebServer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWebServer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WebServer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WebServer
    def Genre(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(1)
def WebServerStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddGenre(builder, genre): builder.PrependUint32Slot(0, genre, 0)
def WebServerAddGenre(builder, genre):
    """This method is deprecated. Please switch to AddGenre."""
    return AddGenre(builder, genre)
def End(builder): return builder.EndObject()
def WebServerEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)